# Site settings
title: Joel Antonio-Vásquez
email: antoniovasquez.joel@gmail.com
description: "遅かれ早かれ、知性 が 規律を破る,
    Japanese Proverb"
baseurl: ""
url: "https://joelantoniov.github.io"
mathexchange_username: antoniov-joel
mathoverflow_username: antoniov-joel
codeforces_username: antoniovasquez.joel
brilliant_username: antoniovasquez.joel

# Build settings
markdown: Kramdown
permalink: pretty
