# Site settings
title: Joel Javier Antonio-Vásquez
email: antoniovasquez.joel@gmail.com
  #description: "遅かれ早かれ、知性 が 規律を破る,
    Japanese Proverb"
baseurl: ""
url: "https://joelantoniov.github.io"

# Build settings
markdown: Kramdown
permalink: pretty
